name: "Deploy Azure VM"
description: "Trigger a Terraform deployment with a custom VM name"
title: "[Deploy] VM: ${vm_name}"
labels: ["terraform", "azure", "deployment"]
body:
  - type: input
    id: vm_name
    attributes:
      label: "VM Name"
      description: "Enter the name for the new Azure VM"
      placeholder: "e.g. lab-vm-01"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: "Environment"
      description: "Select the target environment"
      options:
        - dev
        - staging
        - prod
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: "Additional Notes"
      description: "Optional context or configuration overrides"
      placeholder: "e.g. Use Ubuntu 22.04, attach to subnet-x"

  - type: dropdown
    id: action
    attributes:
      label: "Terraform Action"
      description: "Choose whether to plan or destroy"
      options:
        - plan
        - destroy
    validations:
      required: true
