name: Terraform Azure CI

on:
  push:
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.github/workflows/terraform.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**.tf'
      - '**.tfvars'
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted
    env:
      TF_VAR_arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_admin_password: ${{ secrets.USERPWD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./modules/azure_vm

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ./modules/azure_vm

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./modules/azure_vm

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        working-directory: ./modules/azure_vm

      - name: Terraform Apply (on push to main)
        if: github.event_name == 'push'
        run: terraform apply -input=false -auto-approve tfplan
        working-directory: ./modules/azure_vm